-- Prisma Migrate, applied through the DIRECT transport (DBX-001).
--
-- Written by hand rather than generated by `prisma migrate dev`, which needs a
-- shadow database it is allowed to create and drop. `migration_user` holds no
-- database CREATE by design, so `migrate dev` cannot run here at all -- and
-- `migrate deploy`, which applies committed SQL and creates nothing it was not
-- given, is the production command anyway.
--
-- Unqualified on purpose. The schema this lands in comes from the `schema=`
-- parameter on DIRECT_URL, which names the disposable schema plan §4.4
-- describes: created and dropped through the container-local privileged socket,
-- recorded in root-owned state before this unprivileged fixture ever sees the
-- name, and never one of the protected schemas.

CREATE TABLE "fixture_rows" (
    "id" UUID NOT NULL,
    "label" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "fixture_rows_pkey" PRIMARY KEY ("id")
);
