// Generated by bin/apg.sh generate from notes-tasks-v1+example-note-embeddings-v1 + notes-tasks-agent-v1+example-note-embeddings-agent-v1; do not edit.
//
// The agent plane, over JSON-RPC. The wire shape was READ from the tree
// (rig 23f) rather than remembered: one POST, no `initialize` handshake --
// the runtime is assembled `stateless_http` (ADR 0125) and a bare `tools/call`
// was measured answering 200.
//
// A reply may arrive SSE-framed (`event: message\r\ndata: {...}`), so
// `JSON.parse(body)` throws on a perfectly good answer (D458): the last
// `data:` line wins. And a refusal arrives in EITHER of two places -- a
// top-level `error`, or `result.isError` with the text in `result.content[0]`.
// Reading only `error` passes on a refused write, which is a defect this
// repository has carried against its own live proofs since Session 9.

import { CONTRACT } from "./contract.js";
import type { AgentFilter, AgentRefusal } from "./types.js";

const CALLER_FACING_TOKENS = [
  "approval_required",
  "budget_exceeded",
  "input_not_permitted",
  "resource_unknown",
  "row_not_found",
  "scope_not_held",
  "write_conflict"
] as const;

export type AgentOutcome =
  | { kind: "ok"; content: unknown; structured: unknown }
  | { kind: "refused"; token: AgentRefusal | null; message: string }
  | { kind: "transport"; reason: string };

export type LockReport =
  | { kind: "ok"; toolsSha256: string; toolCount: number; resources: unknown }
  | { kind: "stale_contract"; expected: string; reported: string }
  | { kind: "unconfirmable"; reason: string }
  | { kind: "refused"; token: AgentRefusal | null; message: string }
  | { kind: "transport"; reason: string };

/**
 * A fresh idempotency key.
 *
 * It is a TOOL ARGUMENT, not a header (D1202): an agent supplies
 * `idempotency_key` in `arguments`, and the RUNTIME sets the
 * `Idempotency-Key` header toward PostgREST. A client helper that set a header
 * would be building a request the product never makes.
 */
export function idempotencyKey(): string {
  const bytes = new Uint8Array(16);
  globalThis.crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

export function createAgentClient(options: {
  mcpUrl: string;
  token: string;
  fetchImpl?: typeof fetch;
}) {
  const mcpUrl = options.mcpUrl;
  const token = options.token;
  const call = options.fetchImpl ?? fetch;
  let nextId = 1;

  function messageFrom(body: string, contentType: string): unknown {
    if (contentType.includes("text/event-stream")) {
      let payload: unknown = undefined;
      for (const line of body.split(/\r?\n/)) {
        if (line.startsWith("data: ")) payload = JSON.parse(line.slice(6));
      }
      return payload;
    }
    return JSON.parse(body);
  }

  function tokenIn(message: string): AgentRefusal | null {
    for (const candidate of CALLER_FACING_TOKENS) {
      if (message.includes(candidate)) return candidate as AgentRefusal;
    }
    return null;
  }

  async function callTool(name: string, args: Record<string, unknown>): Promise<AgentOutcome> {
    let response: Response;
    try {
      response = await call(mcpUrl, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
          Accept: "application/json, text/event-stream",
        },
        body: JSON.stringify({
          jsonrpc: "2.0",
          id: nextId++,
          method: "tools/call",
          params: { name, arguments: args },
        }),
      });
    } catch (error) {
      return { kind: "transport", reason: error instanceof Error ? error.name : "fetch failed" };
    }

    const text = await response.text();
    let message: unknown;
    try {
      message = messageFrom(text, response.headers.get("content-type") ?? "");
    } catch {
      return { kind: "transport", reason: "the plane's reply did not parse" };
    }
    const envelope = (message ?? {}) as {
      error?: { message?: unknown };
      result?: { isError?: unknown; content?: unknown; structuredContent?: unknown };
    };

    if (envelope.error) {
      const detail = typeof envelope.error.message === "string" ? envelope.error.message : "";
      return { kind: "refused", token: tokenIn(detail), message: detail };
    }
    const result = envelope.result ?? {};
    if (result.isError === true) {
      const content = (result.content ?? []) as { text?: unknown }[];
      const detail = typeof content[0]?.text === "string" ? content[0].text : "";
      return { kind: "refused", token: tokenIn(detail), message: detail };
    }
    return { kind: "ok", content: result.content, structured: result.structuredContent };
  }

  return {
    callTool,
    idempotencyKey,

    /**
     * The roster, AND a check that the plane loaded the lock this client was
     * generated from.
     *
     * `null` is `unconfirmable`, never `ok`: a lock below schema 4 carries no
     * signature, so the plane has nothing to report and the honest answer is
     * that the question could not be settled (ADR 0195). Reporting it as a
     * match would be the one reading that cannot be recovered from.
     */
    async listResources(): Promise<LockReport> {
      const outcome = await callTool("list_resources", {});
      if (outcome.kind === "transport") return outcome;
      if (outcome.kind === "refused") return outcome;

      const structured = (outcome.structured ?? {}) as {
        lock?: { tools_sha256?: unknown; tool_count?: unknown };
        resources?: unknown;
      };
      const reported = structured.lock?.tools_sha256;
      if (reported === null || reported === undefined) {
        return {
          kind: "unconfirmable",
          reason: "the plane reported no lock digest, so which roster it loaded is unknown",
        };
      }
      if (typeof reported !== "string") {
        return { kind: "unconfirmable", reason: "the reported lock digest is not a string" };
      }
      if (reported !== CONTRACT.toolsSha256) {
        return { kind: "stale_contract", expected: CONTRACT.toolsSha256, reported };
      }
      return {
        kind: "ok",
        toolsSha256: reported,
        toolCount: Number(structured.lock?.tool_count ?? 0),
        resources: structured.resources,
      };
    },

    async createNote(args: { p_title: string, p_content: string, idempotency_key: string, dry_run: boolean }): Promise<AgentOutcome> {
      return callTool("create_note", args as Record<string, unknown>);
    },

    async describeResource(args: { tool: string, resource: string }): Promise<AgentOutcome> {
      return callTool("describe_resource", args as Record<string, unknown>);
    },

    async queryResource(args: { resource: string, columns?: string[], filters?: AgentFilter[], order_by?: number, limit?: number }): Promise<AgentOutcome> {
      return callTool("query_resource", args as Record<string, unknown>);
    },

    async runReport(): Promise<AgentOutcome> {
      return callTool("run_report", {});
    },

    async setNoteEmbedding(args: { p_note_id: string, p_embedding: string, idempotency_key: string, dry_run: boolean }): Promise<AgentOutcome> {
      return callTool("set_note_embedding", args as Record<string, unknown>);
    },

    async updateTaskStatus(args: { p_task_id: string, p_expected_status: string, p_new_status: string, idempotency_key: string, dry_run: boolean }): Promise<AgentOutcome> {
      return callTool("update_task_status", args as Record<string, unknown>);
    },
  };
}

export type AgentClient = ReturnType<typeof createAgentClient>;
