// Generated by bin/apg.sh generate from notes-tasks-v1+example-note-embeddings-v1 + notes-tasks-agent-v1+example-note-embeddings-agent-v1; do not edit.
//
// The canonical form, in JavaScript. This is a SECOND implementation of a rule
// `openapi_normalize.canonical_bytes` already states in Python, and it is
// guarded rather than trusted: `test_canonical_ts_reproduces_pythons_fingerprint`
// runs this file over every committed snapshot in the toolchain image and
// compares each digest to Python's.
//
// Measured (rig 23b): `JSON.stringify(sortKeysDeep(x), null, 2) + "\n"`
// reproduces Python's bytes for every REST and MCP snapshot in the tree. It
// does NOT reproduce the application document, which carries two float literals
// JavaScript prints as integers -- which is why that digest is never compared.

import { createHash } from "node:crypto";

export const SENTINEL_HOST = "project.invalid:443";
export const SENTINEL_BASE_PATH = "/__project_base_path__";
export const REQUIRED_SCHEMES = ["https"];

export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };

/** Every object's keys sorted, recursively. Arrays keep their order. */
export function sortKeysDeep(value: Json): Json {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (value === null || typeof value !== "object") return value;
  const out: { [key: string]: Json } = {};
  for (const key of Object.keys(value).sort()) out[key] = sortKeysDeep(value[key]);
  return out;
}

/** Python's `canonical_bytes`, as text: sorted keys, two-space indent, trailing newline. */
export function canonicalText(document: Json): string {
  return JSON.stringify(sortKeysDeep(document), null, 2) + "\n";
}

export function fingerprint(document: Json): string {
  return createHash("sha256").update(canonicalText(document), "utf8").digest("hex");
}

export type NormalizeResult =
  | { kind: "ok"; document: Json }
  | { kind: "unparsable"; reason: string };

/**
 * The served document, made project-neutral the way the capture makes it.
 *
 * `basePath` is the ONE field asserted (D1207). The capture validates host,
 * basePath and schemes against the deployed document before substituting them;
 * a client holds no deployed document -- it holds a URL it is already connected
 * to. The served `host` carries an explicit `:443` where `new URL(...).host`
 * omits a default port, so comparing them would refuse every correct
 * deployment. Instead: substitute host and schemes unread, assert basePath
 * against the URL we were given, and refuse any RESIDUE of the real values
 * elsewhere -- which is what keeps the substitution honest.
 */
export function normalizeServed(document: Json, restUrl: string): NormalizeResult {
  if (document === null || typeof document !== "object" || Array.isArray(document)) {
    return { kind: "unparsable", reason: "the served document is not a JSON object" };
  }
  const served = document as { [key: string]: Json };
  const host = served.host;
  const basePath = served.basePath;
  if (typeof host !== "string" || typeof basePath !== "string") {
    return { kind: "unparsable", reason: "the served document carries no host or basePath" };
  }

  let expected: string;
  try {
    expected = new URL(restUrl).pathname.replace(/\/+$/, "");
  } catch {
    return { kind: "unparsable", reason: `restUrl is not a URL: ${restUrl}` };
  }
  if (basePath.replace(/\/+$/, "") !== expected) {
    return {
      kind: "unparsable",
      reason: `the document's basePath ${basePath} is not the path of ${restUrl}; this is `
        + "not the service this client was pointed at",
    };
  }

  const neutral: { [key: string]: Json } = { ...served };
  neutral.host = SENTINEL_HOST;
  neutral.basePath = SENTINEL_BASE_PATH;
  neutral.schemes = [...REQUIRED_SCHEMES];

  const residue = JSON.stringify(neutral);
  for (const real of [host, basePath]) {
    if (real.length > 0 && residue.includes(real)) {
      return {
        kind: "unparsable",
        reason: `the document still names ${real} after substitution, so the normalized `
          + "form would not be project-neutral",
      };
    }
  }
  return { kind: "ok", document: neutral };
}
