// Generated by bin/apg.sh generate from notes-tasks-v1+example-note-embeddings-v1 + notes-tasks-agent-v1+example-note-embeddings-agent-v1; do not edit.
//
// Nothing here retries, logs, or prints. The token lives in a closure and never
// reaches a URL, a message or a thrown error (D105). Every call answers with a
// value -- ok, refused, or transport -- rather than throwing, because a refusal
// by the product is not an exception in the caller's program and treating it as
// one is what makes callers swallow it.

import { CONTRACT } from "./contract.js";
import { fingerprint, normalizeServed, type Json } from "./canonical.js";
import type { CreateNoteArgs, CreateTaskArgs, FilterOperator, NoteEmbeddingsColumn, NoteEmbeddingsRow, NotesColumn, NotesRow, PtCode, SetNoteEmbeddingArgs, TasksColumn, TasksRow, UpdateTaskStatusArgs } from "./types.js";

export type Filter<Column extends string> = {
  column: Column;
  op: FilterOperator;
  value: string | number | boolean | null;
};

export type Query<Column extends string> = {
  select?: readonly Column[];
  order?: readonly { column: Column; direction: "asc" | "desc" }[];
  limit?: number;
  filters?: readonly Filter<Column>[];
};

export type Outcome<T> =
  | { kind: "ok"; status: number; body: T }
  | { kind: "refused"; status: number; code: PtCode | string; message: string }
  | { kind: "transport"; reason: string }
  | { kind: "not_initialised" };

export type InitResult =
  | { kind: "ok" }
  | { kind: "stale_contract"; expected: string; served: string }
  | { kind: "unreachable"; reason: string }
  | { kind: "unparsable"; reason: string };

export type ClientOptions = {
  restUrl: string;
  appUrl?: string;
  token: string;
  fetchImpl?: typeof fetch;
};

export function createClient(options: ClientOptions) {
  const restUrl = options.restUrl.replace(/\/+$/, "");
  const appUrl = (options.appUrl ?? "").replace(/\/+$/, "");
  const token = options.token;
  const call = options.fetchImpl ?? fetch;
  let ready = false;

  function headers(extra: Record<string, string> = {}): Record<string, string> {
    return { Authorization: `Bearer ${token}`, ...extra };
  }

  async function classify<T>(response: Response): Promise<Outcome<T>> {
    const text = await response.text();
    let body: unknown = undefined;
    try {
      body = text.length > 0 ? JSON.parse(text) : undefined;
    } catch {
      body = undefined;
    }
    if (response.ok) return { kind: "ok", status: response.status, body: body as T };
    // PostgREST answers a refusal as {code, message, details, hint}. The code is
    // the product's own SQLSTATE, which is why the union is generated from the
    // migrations rather than guessed (ADR 0139).
    const shape = (body ?? {}) as { code?: unknown; message?: unknown };
    return {
      kind: "refused",
      status: response.status,
      code: typeof shape.code === "string" ? shape.code : String(response.status),
      message: typeof shape.message === "string" ? shape.message : "",
    };
  }

  async function request<T>(url: string, init: RequestInit): Promise<Outcome<T>> {
    let response: Response;
    try {
      response = await call(url, init);
    } catch (error) {
      // The reason, never the request: a thrown fetch error can carry the URL,
      // and the URL is the one place a caller might have put a value.
      return { kind: "transport", reason: error instanceof Error ? error.name : "fetch failed" };
    }
    return classify<T>(response);
  }

  function guard<T>(): Outcome<T> | null {
    return ready ? null : { kind: "not_initialised" };
  }

  /**
   * Check that the service is serving the surface this client was generated
   * from, and refuse everything until it does.
   *
   * Three outcomes, and the third is REPORTED rather than folded into one of
   * the first two (ADR 0195): a service that did not answer is `unreachable`,
   * a document that is not the document is `unparsable`, and only an actual
   * fingerprint difference is `stale_contract` -- which names both digests,
   * because "they differ" without the values sends the reader to source.
   */
  async function init(): Promise<InitResult> {
    let response: Response;
    try {
      response = await call(`${restUrl}/`, {
        method: "GET",
        headers: headers({ Accept: "application/openapi+json" }),
      });
    } catch (error) {
      return {
        kind: "unreachable",
        reason: error instanceof Error ? error.name : "fetch failed",
      };
    }
    if (!response.ok) {
      return { kind: "unreachable", reason: `the service answered ${response.status}` };
    }
    let document: Json;
    try {
      document = (await response.json()) as Json;
    } catch {
      return { kind: "unparsable", reason: "the served document is not JSON" };
    }
    const normalized = normalizeServed(document, restUrl);
    if (normalized.kind !== "ok") return { kind: "unparsable", reason: normalized.reason };

    const served = fingerprint(normalized.document);
    if (served !== CONTRACT.restOpenapiSha256) {
      return { kind: "stale_contract", expected: CONTRACT.restOpenapiSha256, served };
    }
    ready = true;
    return { kind: "ok" };
  }

  function buildQuery(query: Query<string> | undefined): string {
    const parts: string[] = [];
    if (query?.select?.length) parts.push(`select=${query.select.join(",")}`);
    for (const filter of query?.filters ?? []) {
      // The value is percent-encoded and the operator comes from a closed
      // union, so a caller value is a VALUE and never syntax (ADR 0127).
      parts.push(
        `${filter.column}=${filter.op}.${encodeURIComponent(String(filter.value))}`,
      );
    }
    if (query?.order?.length) {
      parts.push(
        `order=${query.order.map((o) => `${o.column}.${o.direction}`).join(",")}`,
      );
    }
    if (typeof query?.limit === "number") parts.push(`limit=${query.limit}`);
    return parts.length ? `?${parts.join("&")}` : "";
  }

  return {
    init,
    contract: CONTRACT,

    async listNoteEmbeddings(query?: Query<NoteEmbeddingsColumn>): Promise<Outcome<NoteEmbeddingsRow[]>> {
      const refusal = guard<NoteEmbeddingsRow[]>();
      if (refusal) return refusal;
      return request<NoteEmbeddingsRow[]>(`${restUrl}/note_embeddings${buildQuery(query)}`, {
        method: "GET",
        headers: headers({ Accept: "application/json", Prefer: "count=none" }),
      });
    },

    async listNotes(query?: Query<NotesColumn>): Promise<Outcome<NotesRow[]>> {
      const refusal = guard<NotesRow[]>();
      if (refusal) return refusal;
      return request<NotesRow[]>(`${restUrl}/notes${buildQuery(query)}`, {
        method: "GET",
        headers: headers({ Accept: "application/json", Prefer: "count=none" }),
      });
    },

    async listTasks(query?: Query<TasksColumn>): Promise<Outcome<TasksRow[]>> {
      const refusal = guard<TasksRow[]>();
      if (refusal) return refusal;
      return request<TasksRow[]>(`${restUrl}/tasks${buildQuery(query)}`, {
        method: "GET",
        headers: headers({ Accept: "application/json", Prefer: "count=none" }),
      });
    },

    async createNote(args: CreateNoteArgs): Promise<Outcome<unknown>> {
      const refusal = guard<unknown>();
      if (refusal) return refusal;
      return request<unknown>(`${restUrl}/rpc/create_note`, {
        method: "POST",
        headers: headers({
          "Content-Type": "application/json",
          Accept: "application/json",
          Prefer: "return=representation",
        }),
        body: JSON.stringify(args),
      });
    },

    async createTask(args: CreateTaskArgs): Promise<Outcome<unknown>> {
      const refusal = guard<unknown>();
      if (refusal) return refusal;
      return request<unknown>(`${restUrl}/rpc/create_task`, {
        method: "POST",
        headers: headers({
          "Content-Type": "application/json",
          Accept: "application/json",
          Prefer: "return=representation",
        }),
        body: JSON.stringify(args),
      });
    },

    async setNoteEmbedding(args: SetNoteEmbeddingArgs): Promise<Outcome<unknown>> {
      const refusal = guard<unknown>();
      if (refusal) return refusal;
      return request<unknown>(`${restUrl}/rpc/set_note_embedding`, {
        method: "POST",
        headers: headers({
          "Content-Type": "application/json",
          Accept: "application/json",
          Prefer: "return=representation",
        }),
        body: JSON.stringify(args),
      });
    },

    async updateTaskStatus(args: UpdateTaskStatusArgs): Promise<Outcome<unknown>> {
      const refusal = guard<unknown>();
      if (refusal) return refusal;
      return request<unknown>(`${restUrl}/rpc/update_task_status`, {
        method: "POST",
        headers: headers({
          "Content-Type": "application/json",
          Accept: "application/json",
          Prefer: "return=representation",
        }),
        body: JSON.stringify(args),
      });
    },

    async login(payload: { password: string, username: string }): Promise<Outcome<unknown>> {
      if (!appUrl) return { kind: "transport", reason: "no appUrl was given" };
      return request<unknown>(`${appUrl}/auth/login`, {
        method: "POST",
        headers: headers({
          "Content-Type": "application/json",
          Accept: "application/json",
        }),
        body: JSON.stringify(payload),
      });
    },

    async refresh(payload: { refresh_token: string }): Promise<Outcome<unknown>> {
      const refusal = guard<unknown>();
      if (refusal) return refusal;
      if (!appUrl) return { kind: "transport", reason: "no appUrl was given" };
      return request<unknown>(`${appUrl}/auth/refresh`, {
        method: "POST",
        headers: headers({
          "Content-Type": "application/json",
          Accept: "application/json",
        }),
        body: JSON.stringify(payload),
      });
    },

    async me(): Promise<Outcome<unknown>> {
      const refusal = guard<unknown>();
      if (refusal) return refusal;
      if (!appUrl) return { kind: "transport", reason: "no appUrl was given" };
      return request<unknown>(`${appUrl}/auth/me`, {
        method: "GET",
        headers: headers({
          Accept: "application/json",
        }),

      });
    },
  };
}

export type Client = ReturnType<typeof createClient>;
