// Generated by bin/apg.sh generate from notes-tasks-v1+example-note-embeddings-v1 + notes-tasks-agent-v1+example-note-embeddings-agent-v1; do not edit.
//
// The four artefacts this client is a claim about. `restOpenapiSha256` is the
// ONE that is checked at runtime: `init()` fetches the served REST document as
// the caller and compares its fingerprint to this value (ADR 0204).
//
// `appOpenapiSha256` is provenance and is deliberately never compared: the
// application document is not served to a caller on a route this client holds,
// and its canonical form is not reproducible in JavaScript (two Pydantic floats
// -- rig 23b, D1203).
//
// `toolsSha256` is compared, but against what the agent plane REPORTS it
// loaded, not against a file -- a process cannot be wrong about which lock it
// loaded, and a file can be ahead of the container that reads it (D1152/D1153).

export const CONTRACT = {
  restContractId: "notes-tasks-v1+example-note-embeddings-v1",
  agentContractId: "notes-tasks-agent-v1+example-note-embeddings-agent-v1",
  templateVersion: "1.4.0",
  clientVersion: "1.0.0",
  mergedSurfaceSha256: "4e10c7cc597057c08af690fb7e76394cbd9cf8a0e9e9d5098931714a880fdd40",
  restOpenapiSha256: "808ac715c09aeebc382dd5afc886c1680fe2ea9870e729b9d34a623dee8d18de",
  appOpenapiSha256: "e477fd239291380e4ec0e181dfcc66906fa2a359df3a57522afd437a4ae8b070",
  toolsSha256: "24ac100bcea5f4cf5350c0aa894ec858822c0230d43fe3815d90e17290db3f24",
} as const;
