// Generated by bin/apg.sh generate from notes-tasks-v1+example-note-embeddings-v1 + notes-tasks-agent-v1+example-note-embeddings-agent-v1; do not edit.
//
// A driver, not a library. It reads three values from the environment, calls
// init(), reads one relation and (when asked) calls one function, and prints
// one JSON line per step. Run it inside the toolchain image:
//
//   docker run --rm -v <client>:/work:ro -e APG_REST_URL=... -e APG_TOKEN=... \
//     apg-client-typescript smoke
//
// It prints outcomes. It does not print the token, the URLs, or any row it
// read -- a smoke's output is pasted into issues, and the one value it holds
// is somebody's credential.

import { createClient } from "./client.ts";
import { createAgentClient } from "./agent.ts";
import { CONTRACT } from "./contract.ts";

function say(step: string, detail: Record<string, unknown>): void {
  console.log(JSON.stringify({ step, ...detail }));
}

function required(name: string): string {
  const value = process.env[name];
  if (!value) {
    say("environment", { missing: name });
    process.exit(2);
  }
  return value;
}

const restUrl = required("APG_REST_URL");
const token = required("APG_TOKEN");
const mcpUrl = process.env.APG_MCP_URL ?? "";

let failures = 0;

const client = createClient({ restUrl, appUrl: process.env.APG_APP_URL, token });

const started = await client.init();
say("init", { kind: started.kind,
  ...(started.kind === "stale_contract"
    ? { expected: started.expected, served: started.served }
    : {}),
  ...(started.kind === "unreachable" || started.kind === "unparsable"
    ? { reason: started.reason }
    : {}) });
if (started.kind !== "ok") {
  // Nothing below can mean anything if the surface is not the one this client
  // was generated from, so the driver stops rather than reporting failures
  // whose cause is already known.
  say("done", { ok: false, reason: started.kind });
  process.exit(1);
}

const read = await client.listNoteEmbeddings({ limit: 1 });
say("read", { relation: "note_embeddings", kind: read.kind,
  ...(read.kind === "refused" ? { code: read.code } : {}),
  ...(read.kind === "ok" ? { rows: Array.isArray(read.body) ? read.body.length : 0 } : {}) });
if (read.kind !== "ok") failures += 1;

const probe = process.env.APG_SMOKE_FILTER_VALUE;
if (probe) {
  const filtered = await client.listNotes({
    limit: 1,
    filters: [{ column: "title", op: "eq", value: probe }],
  });
  const detail = filtered.kind === "refused"
    ? { status: filtered.status, code: filtered.code }
    : {};
  say("filter", { relation: "notes",
    column: "title", kind: filtered.kind, ...detail });
  if (filtered.kind !== "ok") failures += 1;
} else {
  say("filter", { skipped: "APG_SMOKE_FILTER_VALUE is not set" });
}

if (process.env.APG_SMOKE_ALLOW_WRITE === "1") {
  const called = await client.createNote({ p_title: "apg-smoke" } as never);
  say("rpc", { name: "create_note", kind: called.kind,
    ...(called.kind === "refused" ? { code: called.code } : {}) });
  if (called.kind !== "ok") failures += 1;
} else {
  say("rpc", { name: "create_note",
    skipped: "APG_SMOKE_ALLOW_WRITE is not 1, and the first reviewed function writes" });
}

if (mcpUrl) {
  const agent = createAgentClient({ mcpUrl, token });
  const roster = await agent.listResources();
  say("lock", { kind: roster.kind,
    ...(roster.kind === "ok" ? { toolCount: roster.toolCount } : {}),
    ...(roster.kind === "stale_contract"
      ? { expected: roster.expected, reported: roster.reported }
      : {}),
    ...(roster.kind === "unconfirmable" ? { reason: roster.reason } : {}) });
  if (roster.kind !== "ok") failures += 1;
} else {
  say("lock", { skipped: "APG_MCP_URL is not set" });
}

say("done", { ok: failures === 0, failures, clientVersion: CONTRACT.clientVersion });
process.exit(failures === 0 ? 0 : 1);
