// Generated by bin/apg.sh generate from notes-tasks-v1+example-note-embeddings-v1 + notes-tasks-agent-v1+example-note-embeddings-agent-v1; do not edit.
//
// Every type here is the REVIEWED surface's, and nothing else is expressible:
// a column outside a relation's list, a filter operator outside the capability
// schema's set, or an argument the contract does not name is not a value these
// unions accept, so such a request cannot be built (ADR 0204).

export type FilterOperator = "eq" | "neq" | "lt" | "lte" | "gt" | "gte" | "in" | "is_null";

// The filter shape a READ TOOL takes. Named here because the agent
// runtime declares `filters` as a list of these, and a client that
// referred to a type nobody emitted would not compile (D1223).
export type AgentFilter = {
  column: string;
  op: FilterOperator;
  value: string | number | boolean | null;
};

// The `PT` SQLSTATEs this release AND this project's own migrations raise.
export type PtCode = "PT401" | "PT403" | "PT404" | "PT409" | "PT412" | "PT422";

// The only tokens an agent may be told (`mcp_errors.CALLER_FACING_TOKENS`).
export type AgentRefusal = "approval_required" | "budget_exceeded" | "input_not_permitted" | "resource_unknown" | "row_not_found" | "scope_not_held" | "write_conflict";

export type TaskStatus = "pending" | "in_progress" | "completed" | "cancelled";

export interface NoteEmbeddingsRow {
  note_id: string | null;
  owner_id: string | null;
  embedding: string | null;
  updated_at: string | null;
}

export type NoteEmbeddingsColumn = "note_id" | "owner_id" | "embedding" | "updated_at";

export interface NotesRow {
  id: string | null;
  owner_id: string | null;
  title: string | null;
  content: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export type NotesColumn = "id" | "owner_id" | "title" | "content" | "created_at" | "updated_at";

export interface TasksRow {
  id: string | null;
  owner_id: string | null;
  note_id: string | null;
  title: string | null;
  description: string | null;
  status: "pending" | "in_progress" | "completed" | "cancelled" | null;
  created_at: string | null;
  updated_at: string | null;
}

export type TasksColumn = "id" | "owner_id" | "note_id" | "title" | "description" | "status" | "created_at" | "updated_at";

export interface CreateNoteArgs {
  p_title: string;
  p_content?: string;
}

export interface CreateTaskArgs {
  p_title: string;
  p_note_id?: string;
}

export interface SetNoteEmbeddingArgs {
  p_note_id: string;
  p_embedding: string;
}

export interface UpdateTaskStatusArgs {
  p_task_id: string;
  p_expected_status: "pending" | "in_progress" | "completed" | "cancelled";
  p_new_status: "pending" | "in_progress" | "completed" | "cancelled";
}
