"""The TypeScript emitter: an :class:`~agentic_postgres.client_ir.IR` in, a package out.

**Reads the IR and nothing else** (ADR 0204). No path under `contracts/` or
`projects/`, no deployed document, no environment, no clock -- asserted by AST
in `tests/contract/test_client_typescript.py`, because an emitter that quietly
read one more file would produce a package nobody could reproduce from the IR
it claims to be generated from.

The emitted package has **no runtime dependency**. That is not minimalism: a
client is held by someone who did not generate it, on a machine this project
will never see, and every dependency is a second thing they have to trust to
believe the digest check below. `node:crypto` is the one import, and it is the
runtime's.

What every generated client does before anything else is `init()`: it fetches
the served REST document **as the caller**, normalizes it the way the capture
does, fingerprints it in the JavaScript canonical form, and compares that to
the digest it was generated with. Rig 23a measured the equality that makes this
work -- the `authenticated` role is served exactly the committed snapshot -- and
rig 23b measured that the JavaScript canonical form reproduces Python's bytes.
Both numbers are in ADR 0204.
"""

from __future__ import annotations

import json
from typing import Any

from agentic_postgres.client_ir import (
    IR,
    AuthOperation,
    Relation,
    Rpc,
    Tool,
)

__all__ = ["BANNER", "SENTINELS", "emit"]

#: Substituted into the emitted `canonical.ts`. Passed in from
#: `openapi_normalize`'s own constants by :func:`emit`'s caller contract below
#: -- read, never retyped, because a sentinel that differed by one character
#: would make every `init()` compare a document normalized differently from the
#: way the capture normalizes it, and the failure would read as a stale
#: contract on a correct deployment.
SENTINELS = ("SENTINEL_HOST", "SENTINEL_BASE_PATH", "REQUIRED_SCHEMES")

BANNER = "// Generated by bin/apg.sh generate from {rest} + {agent}; do not edit."


def emit(
    ir: IR,
    *,
    client_version: str,
    sentinel_host: str,
    sentinel_base_path: str,
    required_schemes: tuple[str, ...],
    typescript_version: str,
    types_node_version: str,
) -> dict[str, str]:
    """The package, as relative path -> file text.

    The sentinels and the toolchain versions are arguments rather than imports
    so this module keeps its one-input property: everything it writes comes from
    the IR or from a value its caller read out of the authority that owns it
    (`openapi_normalize`, `versions.env`).
    """
    banner = BANNER.format(rest=ir.rest_contract_id, agent=ir.agent_contract_id)
    files = {
        "contract.ts": _contract_ts(ir, banner, client_version),
        "canonical.ts": _canonical_ts(banner, sentinel_host, sentinel_base_path, required_schemes),
        "types.ts": _types_ts(ir, banner),
        "client.ts": _client_ts(ir, banner),
        "agent.ts": _agent_ts(ir, banner),
        "package.json": _package_json(ir, client_version, typescript_version, types_node_version),
        "tsconfig.json": _tsconfig_json(),
        "README.md": _readme(ir, client_version),
    }
    _refuse_secrets(files)
    return files


# ---------------------------------------------------------------------------
# the refusal that runs over the emitter's OWN output
# ---------------------------------------------------------------------------

#: Patterns no generated file may contain. Checked here, in the emitter, as well
#: as by a test: a test catches it before a commit, and this catches it before a
#: developer's checkout -- and the two failures are different people's.
_FORBIDDEN = (
    ("a URL carrying userinfo", r"://[^/\s]*:[^/\s]*@"),
    ("a bearer token literal", r"eyJ[A-Za-z0-9_-]{10,}\."),
    ("a private key", r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
)


def _refuse_secrets(files: dict[str, str]) -> None:
    import re

    for path, text in sorted(files.items()):
        for label, pattern in _FORBIDDEN:
            if re.search(pattern, text):
                raise ValueError(
                    f"the emitted {path} contains {label}. A generated file is committed and "
                    "copied; nothing that identifies a caller or a deployment may be in one "
                    "(ADR 0204, D105)"
                )


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def _union(values: tuple[str, ...]) -> str:
    return " | ".join(json.dumps(value) for value in values) if values else "never"


def _literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2)


# ---------------------------------------------------------------------------
# contract.ts -- the only file that carries a digest
# ---------------------------------------------------------------------------


def _contract_ts(ir: IR, banner: str, client_version: str) -> str:
    return f"""{banner}
//
// The four artefacts this client is a claim about. `restOpenapiSha256` is the
// ONE that is checked at runtime: `init()` fetches the served REST document as
// the caller and compares its fingerprint to this value (ADR 0204).
//
// `appOpenapiSha256` is provenance and is deliberately never compared: the
// application document is not served to a caller on a route this client holds,
// and its canonical form is not reproducible in JavaScript (two Pydantic floats
// -- rig 23b, D1203).
//
// `toolsSha256` is compared, but against what the agent plane REPORTS it
// loaded, not against a file -- a process cannot be wrong about which lock it
// loaded, and a file can be ahead of the container that reads it (D1152/D1153).

export const CONTRACT = {{
  restContractId: {json.dumps(ir.rest_contract_id)},
  agentContractId: {json.dumps(ir.agent_contract_id)},
  templateVersion: {json.dumps(ir.template_version)},
  clientVersion: {json.dumps(client_version)},
  mergedSurfaceSha256: {json.dumps(ir.digests.merged_surface_sha256)},
  restOpenapiSha256: {json.dumps(ir.digests.rest_openapi_sha256)},
  appOpenapiSha256: {json.dumps(ir.digests.app_openapi_sha256)},
  toolsSha256: {json.dumps(ir.digests.tools_sha256)},
}} as const;
"""


# ---------------------------------------------------------------------------
# canonical.ts -- the second implementation of one serialization rule
# ---------------------------------------------------------------------------


def _canonical_ts(
    banner: str, sentinel_host: str, sentinel_base_path: str, required_schemes: tuple[str, ...]
) -> str:
    return f"""{banner}
//
// The canonical form, in JavaScript. This is a SECOND implementation of a rule
// `openapi_normalize.canonical_bytes` already states in Python, and it is
// guarded rather than trusted: `test_canonical_ts_reproduces_pythons_fingerprint`
// runs this file over every committed snapshot in the toolchain image and
// compares each digest to Python's.
//
// Measured (rig 23b): `JSON.stringify(sortKeysDeep(x), null, 2) + "\\n"`
// reproduces Python's bytes for every REST and MCP snapshot in the tree. It
// does NOT reproduce the application document, which carries two float literals
// JavaScript prints as integers -- which is why that digest is never compared.

import {{ createHash }} from "node:crypto";

export const SENTINEL_HOST = {json.dumps(sentinel_host)};
export const SENTINEL_BASE_PATH = {json.dumps(sentinel_base_path)};
export const REQUIRED_SCHEMES = {json.dumps(list(required_schemes))};

export type Json = null | boolean | number | string | Json[] | {{ [key: string]: Json }};

/** Every object's keys sorted, recursively. Arrays keep their order. */
export function sortKeysDeep(value: Json): Json {{
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (value === null || typeof value !== "object") return value;
  const out: {{ [key: string]: Json }} = {{}};
  for (const key of Object.keys(value).sort()) out[key] = sortKeysDeep(value[key]);
  return out;
}}

/** Python's `canonical_bytes`, as text: sorted keys, two-space indent, trailing newline. */
export function canonicalText(document: Json): string {{
  return JSON.stringify(sortKeysDeep(document), null, 2) + "\\n";
}}

export function fingerprint(document: Json): string {{
  return createHash("sha256").update(canonicalText(document), "utf8").digest("hex");
}}

export type NormalizeResult =
  | {{ kind: "ok"; document: Json }}
  | {{ kind: "unparsable"; reason: string }};

/**
 * The served document, made project-neutral the way the capture makes it.
 *
 * `basePath` is the ONE field asserted (D1207). The capture validates host,
 * basePath and schemes against the deployed document before substituting them;
 * a client holds no deployed document -- it holds a URL it is already connected
 * to. The served `host` carries an explicit `:443` where `new URL(...).host`
 * omits a default port, so comparing them would refuse every correct
 * deployment. Instead: substitute host and schemes unread, assert basePath
 * against the URL we were given, and refuse any RESIDUE of the real values
 * elsewhere -- which is what keeps the substitution honest.
 */
export function normalizeServed(document: Json, restUrl: string): NormalizeResult {{
  if (document === null || typeof document !== "object" || Array.isArray(document)) {{
    return {{ kind: "unparsable", reason: "the served document is not a JSON object" }};
  }}
  const served = document as {{ [key: string]: Json }};
  const host = served.host;
  const basePath = served.basePath;
  if (typeof host !== "string" || typeof basePath !== "string") {{
    return {{ kind: "unparsable", reason: "the served document carries no host or basePath" }};
  }}

  let expected: string;
  try {{
    expected = new URL(restUrl).pathname.replace(/\\/+$/, "");
  }} catch {{
    return {{ kind: "unparsable", reason: `restUrl is not a URL: ${{restUrl}}` }};
  }}
  if (basePath.replace(/\\/+$/, "") !== expected) {{
    return {{
      kind: "unparsable",
      reason: `the document's basePath ${{basePath}} is not the path of ${{restUrl}}; this is `
        + "not the service this client was pointed at",
    }};
  }}

  const neutral: {{ [key: string]: Json }} = {{ ...served }};
  neutral.host = SENTINEL_HOST;
  neutral.basePath = SENTINEL_BASE_PATH;
  neutral.schemes = [...REQUIRED_SCHEMES];

  const residue = JSON.stringify(neutral);
  for (const real of [host, basePath]) {{
    if (real.length > 0 && residue.includes(real)) {{
      return {{
        kind: "unparsable",
        reason: `the document still names ${{real}} after substitution, so the normalized `
          + "form would not be project-neutral",
      }};
    }}
  }}
  return {{ kind: "ok", document: neutral }};
}}
"""


# ---------------------------------------------------------------------------
# types.ts -- the row and argument shapes
# ---------------------------------------------------------------------------


def _relation_interface(relation: Relation) -> str:
    lines = [f"export interface {_pascal(relation.name)}Row {{"]
    for column in relation.columns:
        lines.append(f"  {column.name}: {column.ts_type} | null;")
    lines.append("}")
    lines.append("")
    lines.append(
        f"export type {_pascal(relation.name)}Column = "
        f"{_union(tuple(column.name for column in relation.columns))};"
    )
    return "\n".join(lines)


def _pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_"))


def _types_ts(ir: IR, banner: str) -> str:
    parts = [
        banner,
        "//",
        "// Every type here is the REVIEWED surface's, and nothing else is expressible:",
        "// a column outside a relation's list, a filter operator outside the capability",
        "// schema's set, or an argument the contract does not name is not a value these",
        "// unions accept, so such a request cannot be built (ADR 0204).",
        "",
        f"export type FilterOperator = {_union(ir.filter_operators)};",
        "",
        "// The filter shape a READ TOOL takes. Named here because the agent",
        "// runtime declares `filters` as a list of these, and a client that",
        "// referred to a type nobody emitted would not compile (D1223).",
        "export type AgentFilter = {",
        "  column: string;",
        "  op: FilterOperator;",
        "  value: string | number | boolean | null;",
        "};",
        "",
        "// The `PT` SQLSTATEs this release AND this project's own migrations raise.",
        f"export type PtCode = {_union(ir.pt_codes)};",
        "",
        "// The only tokens an agent may be told (`mcp_errors.CALLER_FACING_TOKENS`).",
        f"export type AgentRefusal = {_union(ir.caller_facing_tokens)};",
        "",
    ]
    for name, values in sorted(ir.enums.items()):
        parts.append(f"export type {_pascal(name)} = {_union(values)};")
    parts.append("")
    for relation in ir.relations:
        parts.append(_relation_interface(relation))
        parts.append("")
    for rpc in ir.rpcs:
        parts.append(f"export interface {_pascal(rpc.name)}Args {{")
        for argument in rpc.arguments:
            optional = "" if argument.required else "?"
            parts.append(f"  {argument.name}{optional}: {argument.ts_type};")
        parts.append("}")
        parts.append("")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# client.ts
# ---------------------------------------------------------------------------


def _client_ts(ir: IR, banner: str) -> str:
    relation_methods = "\n\n".join(_relation_method(relation) for relation in ir.relations)
    rpc_methods = "\n\n".join(_rpc_method(rpc) for rpc in ir.rpcs)
    auth_methods = "\n\n".join(_auth_method(operation) for operation in ir.auth)
    row_imports = ", ".join(
        sorted(
            [f"{_pascal(relation.name)}Row" for relation in ir.relations]
            + [f"{_pascal(relation.name)}Column" for relation in ir.relations]
            + [f"{_pascal(rpc.name)}Args" for rpc in ir.rpcs]
            + ["FilterOperator", "PtCode"]
        )
    )
    return f"""{banner}
//
// Nothing here retries, logs, or prints. The token lives in a closure and never
// reaches a URL, a message or a thrown error (D105). Every call answers with a
// value -- ok, refused, or transport -- rather than throwing, because a refusal
// by the product is not an exception in the caller's program and treating it as
// one is what makes callers swallow it.

import {{ CONTRACT }} from "./contract.js";
import {{ fingerprint, normalizeServed, type Json }} from "./canonical.js";
import type {{ {row_imports} }} from "./types.js";

export type Filter<Column extends string> = {{
  column: Column;
  op: FilterOperator;
  value: string | number | boolean | null;
}};

export type Query<Column extends string> = {{
  select?: readonly Column[];
  order?: readonly {{ column: Column; direction: "asc" | "desc" }}[];
  limit?: number;
  filters?: readonly Filter<Column>[];
}};

export type Outcome<T> =
  | {{ kind: "ok"; status: number; body: T }}
  | {{ kind: "refused"; status: number; code: PtCode | string; message: string }}
  | {{ kind: "transport"; reason: string }}
  | {{ kind: "not_initialised" }};

export type InitResult =
  | {{ kind: "ok" }}
  | {{ kind: "stale_contract"; expected: string; served: string }}
  | {{ kind: "unreachable"; reason: string }}
  | {{ kind: "unparsable"; reason: string }};

export type ClientOptions = {{
  restUrl: string;
  appUrl?: string;
  token: string;
  fetchImpl?: typeof fetch;
}};

export function createClient(options: ClientOptions) {{
  const restUrl = options.restUrl.replace(/\\/+$/, "");
  const appUrl = (options.appUrl ?? "").replace(/\\/+$/, "");
  const token = options.token;
  const call = options.fetchImpl ?? fetch;
  let ready = false;

  function headers(extra: Record<string, string> = {{}}): Record<string, string> {{
    return {{ Authorization: `Bearer ${{token}}`, ...extra }};
  }}

  async function classify<T>(response: Response): Promise<Outcome<T>> {{
    const text = await response.text();
    let body: unknown = undefined;
    try {{
      body = text.length > 0 ? JSON.parse(text) : undefined;
    }} catch {{
      body = undefined;
    }}
    if (response.ok) return {{ kind: "ok", status: response.status, body: body as T }};
    // PostgREST answers a refusal as {{code, message, details, hint}}. The code is
    // the product's own SQLSTATE, which is why the union is generated from the
    // migrations rather than guessed (ADR 0139).
    const shape = (body ?? {{}}) as {{ code?: unknown; message?: unknown }};
    return {{
      kind: "refused",
      status: response.status,
      code: typeof shape.code === "string" ? shape.code : String(response.status),
      message: typeof shape.message === "string" ? shape.message : "",
    }};
  }}

  async function request<T>(url: string, init: RequestInit): Promise<Outcome<T>> {{
    let response: Response;
    try {{
      response = await call(url, init);
    }} catch (error) {{
      // The reason, never the request: a thrown fetch error can carry the URL,
      // and the URL is the one place a caller might have put a value.
      return {{ kind: "transport", reason: error instanceof Error ? error.name : "fetch failed" }};
    }}
    return classify<T>(response);
  }}

  function guard<T>(): Outcome<T> | null {{
    return ready ? null : {{ kind: "not_initialised" }};
  }}

  /**
   * Check that the service is serving the surface this client was generated
   * from, and refuse everything until it does.
   *
   * Three outcomes, and the third is REPORTED rather than folded into one of
   * the first two (ADR 0195): a service that did not answer is `unreachable`,
   * a document that is not the document is `unparsable`, and only an actual
   * fingerprint difference is `stale_contract` -- which names both digests,
   * because "they differ" without the values sends the reader to source.
   */
  async function init(): Promise<InitResult> {{
    let response: Response;
    try {{
      response = await call(`${{restUrl}}/`, {{
        method: "GET",
        headers: headers({{ Accept: "application/openapi+json" }}),
      }});
    }} catch (error) {{
      return {{
        kind: "unreachable",
        reason: error instanceof Error ? error.name : "fetch failed",
      }};
    }}
    if (!response.ok) {{
      return {{ kind: "unreachable", reason: `the service answered ${{response.status}}` }};
    }}
    let document: Json;
    try {{
      document = (await response.json()) as Json;
    }} catch {{
      return {{ kind: "unparsable", reason: "the served document is not JSON" }};
    }}
    const normalized = normalizeServed(document, restUrl);
    if (normalized.kind !== "ok") return {{ kind: "unparsable", reason: normalized.reason }};

    const served = fingerprint(normalized.document);
    if (served !== CONTRACT.restOpenapiSha256) {{
      return {{ kind: "stale_contract", expected: CONTRACT.restOpenapiSha256, served }};
    }}
    ready = true;
    return {{ kind: "ok" }};
  }}

  function buildQuery(query: Query<string> | undefined): string {{
    const parts: string[] = [];
    if (query?.select?.length) parts.push(`select=${{query.select.join(",")}}`);
    for (const filter of query?.filters ?? []) {{
      // The value is percent-encoded and the operator comes from a closed
      // union, so a caller value is a VALUE and never syntax (ADR 0127).
      parts.push(
        `${{filter.column}}=${{filter.op}}.${{encodeURIComponent(String(filter.value))}}`,
      );
    }}
    if (query?.order?.length) {{
      parts.push(
        `order=${{query.order.map((o) => `${{o.column}}.${{o.direction}}`).join(",")}}`,
      );
    }}
    if (typeof query?.limit === "number") parts.push(`limit=${{query.limit}}`);
    return parts.length ? `?${{parts.join("&")}}` : "";
  }}

  return {{
    init,
    contract: CONTRACT,

{_indent(relation_methods, 4)}

{_indent(rpc_methods, 4)}

{_indent(auth_methods, 4)}
  }};
}}

export type Client = ReturnType<typeof createClient>;
"""


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def _relation_method(relation: Relation) -> str:
    name = _camel(f"list_{relation.name}")
    row = f"{_pascal(relation.name)}Row"
    column = f"{_pascal(relation.name)}Column"
    return f"""async {name}(query?: Query<{column}>): Promise<Outcome<{row}[]>> {{
  const refusal = guard<{row}[]>();
  if (refusal) return refusal;
  return request<{row}[]>(`${{restUrl}}/{relation.name}${{buildQuery(query)}}`, {{
    method: "GET",
    headers: headers({{ Accept: "application/json", Prefer: "count=none" }}),
  }});
}},"""


def _rpc_method(rpc: Rpc) -> str:
    name = _camel(rpc.name)
    args = f"{_pascal(rpc.name)}Args"
    return f"""async {name}(args: {args}): Promise<Outcome<unknown>> {{
  const refusal = guard<unknown>();
  if (refusal) return refusal;
  return request<unknown>(`${{restUrl}}{rpc.path}`, {{
    method: "POST",
    headers: headers({{
      "Content-Type": "application/json",
      Accept: "application/json",
      Prefer: "return=representation",
    }}),
    body: JSON.stringify(args),
  }});
}},"""


def _auth_method(operation: AuthOperation) -> str:
    name = _camel(operation.name)
    fields = ", ".join(
        f"{argument.name}{'' if argument.required else '?'}: {argument.ts_type}"
        for argument in operation.request
    )
    signature = f"payload: {{ {fields} }}" if operation.request else ""
    body = "    body: JSON.stringify(payload)," if operation.request else ""
    content = '      "Content-Type": "application/json",\n' if operation.request else ""
    # `login` is exempt from the readiness guard: a caller may need a token
    # before it has one to call `init()` with.
    guard_lines = (
        ""
        if operation.name == "login"
        else "  const refusal = guard<unknown>();\n  if (refusal) return refusal;\n"
    )
    return f"""async {name}({signature}): Promise<Outcome<unknown>> {{
{guard_lines}  if (!appUrl) return {{ kind: "transport", reason: "no appUrl was given" }};
  return request<unknown>(`${{appUrl}}{operation.path}`, {{
    method: "{operation.method}",
    headers: headers({{
{content}      Accept: "application/json",
    }}),
{body}
  }});
}},"""


# ---------------------------------------------------------------------------
# agent.ts
# ---------------------------------------------------------------------------


def _agent_ts(ir: IR, banner: str) -> str:
    # `list_resources` is written by hand below, because it does more than call
    # the tool: it compares the digest the plane reports to the one this client
    # was generated from. Emitting it from the roster as well produced two
    # members of one name and the package did not compile (D1223) -- found by
    # typechecking the emitter's output in the pinned image, which is the only
    # thing that could have found it.
    methods = "\n\n".join(_tool_method(tool) for tool in ir.tools if tool.name != "list_resources")
    return f"""{banner}
//
// The agent plane, over JSON-RPC. The wire shape was READ from the tree
// (rig 23f) rather than remembered: one POST, no `initialize` handshake --
// the runtime is assembled `stateless_http` (ADR 0125) and a bare `tools/call`
// was measured answering 200.
//
// A reply may arrive SSE-framed (`event: message\\r\\ndata: {{...}}`), so
// `JSON.parse(body)` throws on a perfectly good answer (D458): the last
// `data:` line wins. And a refusal arrives in EITHER of two places -- a
// top-level `error`, or `result.isError` with the text in `result.content[0]`.
// Reading only `error` passes on a refused write, which is a defect this
// repository has carried against its own live proofs since Session 9.

import {{ CONTRACT }} from "./contract.js";
import type {{ AgentFilter, AgentRefusal }} from "./types.js";

const CALLER_FACING_TOKENS = {_literal(list(ir.caller_facing_tokens))} as const;

export type AgentOutcome =
  | {{ kind: "ok"; content: unknown; structured: unknown }}
  | {{ kind: "refused"; token: AgentRefusal | null; message: string }}
  | {{ kind: "transport"; reason: string }};

export type LockReport =
  | {{ kind: "ok"; toolsSha256: string; toolCount: number; resources: unknown }}
  | {{ kind: "stale_contract"; expected: string; reported: string }}
  | {{ kind: "unconfirmable"; reason: string }}
  | {{ kind: "refused"; token: AgentRefusal | null; message: string }}
  | {{ kind: "transport"; reason: string }};

/**
 * A fresh idempotency key.
 *
 * It is a TOOL ARGUMENT, not a header (D1202): an agent supplies
 * `idempotency_key` in `arguments`, and the RUNTIME sets the
 * `Idempotency-Key` header toward PostgREST. A client helper that set a header
 * would be building a request the product never makes.
 */
export function idempotencyKey(): string {{
  const bytes = new Uint8Array(16);
  globalThis.crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}}

export function createAgentClient(options: {{
  mcpUrl: string;
  token: string;
  fetchImpl?: typeof fetch;
}}) {{
  const mcpUrl = options.mcpUrl;
  const token = options.token;
  const call = options.fetchImpl ?? fetch;
  let nextId = 1;

  function messageFrom(body: string, contentType: string): unknown {{
    if (contentType.includes("text/event-stream")) {{
      let payload: unknown = undefined;
      for (const line of body.split(/\\r?\\n/)) {{
        if (line.startsWith("data: ")) payload = JSON.parse(line.slice(6));
      }}
      return payload;
    }}
    return JSON.parse(body);
  }}

  function tokenIn(message: string): AgentRefusal | null {{
    for (const candidate of CALLER_FACING_TOKENS) {{
      if (message.includes(candidate)) return candidate as AgentRefusal;
    }}
    return null;
  }}

  async function callTool(name: string, args: Record<string, unknown>): Promise<AgentOutcome> {{
    let response: Response;
    try {{
      response = await call(mcpUrl, {{
        method: "POST",
        headers: {{
          Authorization: `Bearer ${{token}}`,
          "Content-Type": "application/json",
          Accept: "application/json, text/event-stream",
        }},
        body: JSON.stringify({{
          jsonrpc: "2.0",
          id: nextId++,
          method: "tools/call",
          params: {{ name, arguments: args }},
        }}),
      }});
    }} catch (error) {{
      return {{ kind: "transport", reason: error instanceof Error ? error.name : "fetch failed" }};
    }}

    const text = await response.text();
    let message: unknown;
    try {{
      message = messageFrom(text, response.headers.get("content-type") ?? "");
    }} catch {{
      return {{ kind: "transport", reason: "the plane's reply did not parse" }};
    }}
    const envelope = (message ?? {{}}) as {{
      error?: {{ message?: unknown }};
      result?: {{ isError?: unknown; content?: unknown; structuredContent?: unknown }};
    }};

    if (envelope.error) {{
      const detail = typeof envelope.error.message === "string" ? envelope.error.message : "";
      return {{ kind: "refused", token: tokenIn(detail), message: detail }};
    }}
    const result = envelope.result ?? {{}};
    if (result.isError === true) {{
      const content = (result.content ?? []) as {{ text?: unknown }}[];
      const detail = typeof content[0]?.text === "string" ? content[0].text : "";
      return {{ kind: "refused", token: tokenIn(detail), message: detail }};
    }}
    return {{ kind: "ok", content: result.content, structured: result.structuredContent }};
  }}

  return {{
    callTool,
    idempotencyKey,

    /**
     * The roster, AND a check that the plane loaded the lock this client was
     * generated from.
     *
     * `null` is `unconfirmable`, never `ok`: a lock below schema 4 carries no
     * signature, so the plane has nothing to report and the honest answer is
     * that the question could not be settled (ADR 0195). Reporting it as a
     * match would be the one reading that cannot be recovered from.
     */
    async listResources(): Promise<LockReport> {{
      const outcome = await callTool("list_resources", {{}});
      if (outcome.kind === "transport") return outcome;
      if (outcome.kind === "refused") return outcome;

      const structured = (outcome.structured ?? {{}}) as {{
        lock?: {{ tools_sha256?: unknown; tool_count?: unknown }};
        resources?: unknown;
      }};
      const reported = structured.lock?.tools_sha256;
      if (reported === null || reported === undefined) {{
        return {{
          kind: "unconfirmable",
          reason: "the plane reported no lock digest, so which roster it loaded is unknown",
        }};
      }}
      if (typeof reported !== "string") {{
        return {{ kind: "unconfirmable", reason: "the reported lock digest is not a string" }};
      }}
      if (reported !== CONTRACT.toolsSha256) {{
        return {{ kind: "stale_contract", expected: CONTRACT.toolsSha256, reported }};
      }}
      return {{
        kind: "ok",
        toolsSha256: reported,
        toolCount: Number(structured.lock?.tool_count ?? 0),
        resources: structured.resources,
      }};
    }},

{_indent(methods, 4)}
  }};
}}

export type AgentClient = ReturnType<typeof createAgentClient>;
"""


def _tool_method(tool: Tool) -> str:
    name = _camel(tool.name)
    if not tool.arguments:
        return f"""async {name}(): Promise<AgentOutcome> {{
  return callTool({json.dumps(tool.name)}, {{}});
}},"""
    fields = ", ".join(
        f"{argument.name}{'' if argument.required else '?'}: {argument.ts_type}"
        for argument in tool.arguments
    )
    return f"""async {name}(args: {{ {fields} }}): Promise<AgentOutcome> {{
  return callTool({json.dumps(tool.name)}, args as Record<string, unknown>);
}},"""


# ---------------------------------------------------------------------------
# the package files
# ---------------------------------------------------------------------------


def _package_json(ir: IR, client_version: str, typescript_version: str, types_node: str) -> str:
    return (
        json.dumps(
            {
                "name": f"{ir.rest_contract_id}-client",
                "version": client_version,
                "private": True,
                "type": "module",
                "description": (
                    f"Generated typed client for {ir.rest_contract_id}. "
                    "No runtime dependency; verifies the served surface at init()."
                ),
                "dependencies": {},
                "devDependencies": {
                    "typescript": typescript_version,
                    "@types/node": types_node,
                },
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def _tsconfig_json() -> str:
    return (
        json.dumps(
            {
                "compilerOptions": {
                    "strict": True,
                    "module": "nodenext",
                    "moduleResolution": "nodenext",
                    "target": "es2022",
                    "lib": ["es2022", "dom"],
                    "noEmit": True,
                    "types": ["node"],
                    "skipLibCheck": True,
                }
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def _readme(ir: IR, client_version: str) -> str:
    relations = "\n".join(f"- `{relation.name}`" for relation in ir.relations)
    rpcs = "\n".join(f"- `{rpc.name}`" for rpc in ir.rpcs)
    tools = "\n".join(f"- `{tool.name}` ({tool.kind})" for tool in ir.tools)
    return f"""# {ir.rest_contract_id} client {client_version}

Generated by `bin/apg.sh generate`. **Do not edit these files** — regenerate
them; `bin/apg.sh generate --project FILE --check` fails if they have drifted.

## Call `init()` first

```ts
const client = createClient({{ restUrl, appUrl, token }});
const started = await client.init();
if (started.kind !== "ok") throw new Error(started.kind);
```

`init()` fetches the REST service's own OpenAPI document **as you**, normalizes
it the way this project's capture does, and compares the fingerprint to the one
embedded in `contract.ts`. Until it answers `ok`, every other method returns
`{{ kind: "not_initialised" }}`.

It has four answers, and the difference between them matters:

| answer | what it means |
|---|---|
| `ok` | the service is serving the surface this client was generated from |
| `stale_contract` | it is serving a *different* surface — both digests are named |
| `unreachable` | the service did not answer; nothing is known about its surface |
| `unparsable` | it answered something that is not that document |

`unreachable` is never reported as `stale_contract`. A client that could not
reach a service knows nothing about its contract, and saying otherwise would
send you to re-capture a snapshot that was already right.

## What this client holds

Only what you gave it. No credential, no URL, no key is generated into any file
here; the token lives in a closure and never reaches a URL, a log or an error.
Nothing in this package prints.

## The surface

Relations:

{relations}

Functions:

{rpcs}

Agent tools:

{tools}

`agent.ts`'s `listResources()` also checks the digest of the lock the **running**
agent plane loaded against the one this client was generated from. A plane can
serve a different roster than the file its deployment was rendered from, and a
process cannot be wrong about which lock it loaded.

## Digests

| field | checked? |
|---|---|
| `restOpenapiSha256` | yes, at `init()`, against the served document |
| `toolsSha256` | yes, at `listResources()`, against what the plane reports |
| `appOpenapiSha256` | no — provenance only |
| `mergedSurfaceSha256` | no — provenance only |
"""
