"""The four storage calls, each one function of migration 0014's plane.

`storage_service` holds **no privilege of any kind on `app_private.storage_objects`**
-- not SELECT, not INSERT (Run 3, Run 4). Everything below goes through a
SECURITY DEFINER function, and that is what makes the ownership filter
unbypassable by this code rather than merely unbypassed by it: there is no
statement this role could issue that reads a row it does not own, however the
service is later edited.

**Each method is one autocommit round trip and holds nothing open.** ADR 0104's
reasoning applies to completion in particular: the `HeadObject` that produces
`verified_bytes` happens between two calls here, not inside one, because a
transaction held across a network call to a third party is a lock whose duration
is set by that third party.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any
from uuid import UUID

from psycopg.rows import dict_row
from psycopg_pool import AsyncConnectionPool


@dataclass(frozen=True, slots=True)
class DownloadTarget:
    """What a download URL is minted over. Owned and available, or nothing."""

    object_key: str
    content_type: str | None
    verified_bytes: int | None


class StorageRepository:
    """The pool, and the four calls. Holds no state of its own."""

    def __init__(self, pool: AsyncConnectionPool) -> None:
        self._pool = pool

    async def _one(self, statement: str, parameters: tuple[Any, ...]) -> dict[str, Any] | None:
        async with self._pool.connection() as connection:
            cursor = connection.cursor(row_factory=dict_row)
            await cursor.execute(statement, parameters)
            return await cursor.fetchone()

    async def create_intent(
        self,
        *,
        owner_id: UUID,
        object_key: str,
        content_type: str | None,
        declared_bytes: int,
        ttl_seconds: int,
    ) -> UUID:
        """Insert one pending object and return its id.

        The key is generated by the service and passed in. There is no code path
        by which a client-supplied key reaches this argument, because the
        request model has no key or bucket field at all -- which is what
        `STO-KEY-001` asserts, and asserting it on the model is stronger than
        asserting it here.
        """
        row = await self._one(
            "SELECT app_private.storage_create_upload_intent(%s, %s, %s, %s, %s) AS id",
            (owner_id, object_key, content_type, declared_bytes, ttl_seconds),
        )
        assert row is not None  # a scalar function always returns a row
        return row["id"]

    async def complete(self, *, object_id: UUID, owner_id: UUID, verified_bytes: int) -> str | None:
        """Compare-and-set on `state = pending`. Returns the resulting state.

        Three outcomes, and the caller must keep them apart:

        * `"available"` -- this call moved it, or a previous identical call did.
          Completion is idempotent because the CAS matches zero rows the second
          time and the function then reports the state the row is already in.
        * another state -- the owner's object exists and cannot be completed.
        * `None` -- absent, another owner's, or unknown. **Indistinguishable by
          construction**: the function's second query is also filtered on
          `owner_id`, so this code never learns which of the three it had.
        """
        row = await self._one(
            "SELECT app_private.storage_complete_upload(%s, %s, %s) AS state",
            (object_id, owner_id, verified_bytes),
        )
        assert row is not None
        return row["state"]

    async def lookup_for_download(
        self, *, object_id: UUID, owner_id: UUID
    ) -> DownloadTarget | None:
        """Owned and available only. `None` for the other four cases.

        **This lookup is the linearization point** for the tombstone/download
        race, and the ordering is the database's rather than this service's: a
        tombstone that has committed before this statement runs means no URL is
        granted. Deciding it here -- read the state, then decide -- would put a
        window between the two where a commit can land.
        """
        row = await self._one(
            "SELECT object_key, content_type, verified_bytes "
            "FROM app_private.storage_lookup_for_download(%s, %s)",
            (object_id, owner_id),
        )
        if row is None:
            return None
        return DownloadTarget(
            object_key=row["object_key"],
            content_type=row["content_type"],
            verified_bytes=row["verified_bytes"],
        )

    async def completion_key(self, *, object_id: UUID, owner_id: UUID) -> str | None:
        """The key of an object this subject may still complete, or None.

        Migration **0015**, which exists because 0014 had no way to reach it:
        the key was visible only through `lookup_for_download` (available only)
        and `claim_cleanup_batch` (tombstoned only), so the state completion
        operates on was the one state with no reader.

        Returning it from `create_intent` and having the client send it back was
        the alternative, and STO-KEY-001 refuses it -- the request model has no
        key field so that a client-supplied key can never reach a presign.

        **`pending` OR `available`**, so a retried completion can reach the CAS
        that makes it idempotent. A pending-only filter 404s the second call,
        which is what the first version of this did.
        """
        row = await self._one(
            "SELECT app_private.storage_completion_key(%s, %s) AS object_key",
            (object_id, owner_id),
        )
        assert row is not None
        return row["object_key"]

    async def tombstone(self, *, object_id: UUID, owner_id: UUID) -> bool:
        """True when this call moved the object.

        False covers already-tombstoned, absent and another owner's alike, and
        the service answers all of them the same way. It does not answer 404 on
        a false: deleting something already deleted is the caller's intent
        already satisfied, and reporting that as absent would make DELETE
        non-idempotent for the owner.
        """
        row = await self._one(
            "SELECT app_private.storage_tombstone(%s, %s) AS moved",
            (object_id, owner_id),
        )
        assert row is not None
        return bool(row["moved"])
