"""The four storage calls, each one function of migration 0014's plane.

`storage_service` holds **no privilege of any kind on `app_private.storage_objects`**
-- not SELECT, not INSERT (Run 3, Run 4). Everything below goes through a
SECURITY DEFINER function, and that is what makes the ownership filter
unbypassable by this code rather than merely unbypassed by it: there is no
statement this role could issue that reads a row it does not own, however the
service is later edited.

**Each method is one autocommit round trip and holds nothing open.** ADR 0104's
reasoning applies to completion in particular: the `HeadObject` that produces
`verified_bytes` happens between two calls here, not inside one, because a
transaction held across a network call to a third party is a lock whose duration
is set by that third party.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any
from uuid import UUID

from psycopg.rows import dict_row
from psycopg_pool import AsyncConnectionPool


@dataclass(frozen=True, slots=True)
class DownloadTarget:
    """What a download URL is minted over. Owned and available, or nothing."""

    object_key: str
    content_type: str | None
    verified_bytes: int | None


@dataclass(frozen=True, slots=True)
class CleanupClaim:
    """One leased tombstone: what to delete, and how often it has been tried.

    `attempts` is incremented on CLAIM rather than on success (0014), so an
    object that repeatedly kills its worker is visible. Counting successes would
    leave the pathological case indistinguishable from the untouched one.
    """

    object_id: UUID
    object_key: str
    attempts: int


class StorageRepository:
    """The pool, and the four calls. Holds no state of its own."""

    def __init__(self, pool: AsyncConnectionPool) -> None:
        self._pool = pool

    async def _one(self, statement: str, parameters: tuple[Any, ...]) -> dict[str, Any] | None:
        async with self._pool.connection() as connection:
            cursor = connection.cursor(row_factory=dict_row)
            await cursor.execute(statement, parameters)
            return await cursor.fetchone()

    async def create_intent(
        self,
        *,
        owner_id: UUID,
        object_key: str,
        content_type: str | None,
        declared_bytes: int,
        ttl_seconds: int,
    ) -> UUID:
        """Insert one pending object and return its id.

        The key is generated by the service and passed in. There is no code path
        by which a client-supplied key reaches this argument, because the
        request model has no key or bucket field at all -- which is what
        `STO-KEY-001` asserts, and asserting it on the model is stronger than
        asserting it here.
        """
        row = await self._one(
            "SELECT app_private.storage_create_upload_intent(%s, %s, %s, %s, %s) AS id",
            (owner_id, object_key, content_type, declared_bytes, ttl_seconds),
        )
        assert row is not None  # a scalar function always returns a row
        return row["id"]

    async def complete(self, *, object_id: UUID, owner_id: UUID, verified_bytes: int) -> str | None:
        """Compare-and-set on `state = pending`. Returns the resulting state.

        Three outcomes, and the caller must keep them apart:

        * `"available"` -- this call moved it, or a previous identical call did.
          Completion is idempotent because the CAS matches zero rows the second
          time and the function then reports the state the row is already in.
        * another state -- the owner's object exists and cannot be completed.
        * `None` -- absent, another owner's, or unknown. **Indistinguishable by
          construction**: the function's second query is also filtered on
          `owner_id`, so this code never learns which of the three it had.
        """
        row = await self._one(
            "SELECT app_private.storage_complete_upload(%s, %s, %s) AS state",
            (object_id, owner_id, verified_bytes),
        )
        assert row is not None
        return row["state"]

    async def lookup_for_download(
        self, *, object_id: UUID, owner_id: UUID
    ) -> DownloadTarget | None:
        """Owned and available only. `None` for the other four cases.

        **This lookup is the linearization point** for the tombstone/download
        race, and the ordering is the database's rather than this service's: a
        tombstone that has committed before this statement runs means no URL is
        granted. Deciding it here -- read the state, then decide -- would put a
        window between the two where a commit can land.
        """
        row = await self._one(
            "SELECT object_key, content_type, verified_bytes "
            "FROM app_private.storage_lookup_for_download(%s, %s)",
            (object_id, owner_id),
        )
        if row is None:
            return None
        return DownloadTarget(
            object_key=row["object_key"],
            content_type=row["content_type"],
            verified_bytes=row["verified_bytes"],
        )

    async def completion_key(self, *, object_id: UUID, owner_id: UUID) -> str | None:
        """The key of an object this subject may still complete, or None.

        Migration **0015**, which exists because 0014 had no way to reach it:
        the key was visible only through `lookup_for_download` (available only)
        and `claim_cleanup_batch` (tombstoned only), so the state completion
        operates on was the one state with no reader.

        Returning it from `create_intent` and having the client send it back was
        the alternative, and STO-KEY-001 refuses it -- the request model has no
        key field so that a client-supplied key can never reach a presign.

        **`pending` OR `available`**, so a retried completion can reach the CAS
        that makes it idempotent. A pending-only filter 404s the second call,
        which is what the first version of this did.
        """
        row = await self._one(
            "SELECT app_private.storage_completion_key(%s, %s) AS object_key",
            (object_id, owner_id),
        )
        assert row is not None
        return row["object_key"]

    # -- cleanup -------------------------------------------------------------
    #
    # **These three had no caller for five runs.** 0014 released the cleanup
    # plane in Run 3 and nothing in the product called any of it until Run 8;
    # the only exercise they had was SQL written inside two test modules. That
    # is D348 exactly -- *a plane is complete when a caller can be written
    # against it, not when its tests pass* -- and writing the caller is what
    # exposed the missing write-window predicate that migration 0016 adds.
    #
    # None of the three is owner-scoped. Cleanup is not somebody's request: it
    # runs as the deployment, over every owner's tombstones, which is why they
    # take a HOLDER rather than a subject.

    async def _all(self, statement: str, parameters: tuple[Any, ...]) -> list[dict[str, Any]]:
        async with self._pool.connection() as connection:
            cursor = connection.cursor(row_factory=dict_row)
            await cursor.execute(statement, parameters)
            return list(await cursor.fetchall())

    async def expire_intents(self, *, limit: int) -> int:
        """Tombstone pending objects past their deadline. Returns how many moved.

        Bounded, for the reason every sweep here is: an unbounded write over a
        table that has grown is a statement whose duration nobody chose.

        (The wording avoids the SQL verb deliberately.
        `test_the_repository_holds_no_privilege_of_its_own` scans this module's
        source text for statement keywords, and it cannot tell prose from code.
        A conservative scan is the right kind, so the prose moves.)
        """
        row = await self._one(
            "SELECT app_private.storage_expire_intents(%s) AS moved",
            (limit,),
        )
        assert row is not None
        return int(row["moved"])

    async def claim_cleanup_batch(
        self, *, holder: str, limit: int, lease_seconds: int, write_grace_seconds: int
    ) -> list[CleanupClaim]:
        """Lease a batch of collectable tombstones.

        The lease outlives this transaction and that is the whole point (ADR
        0104): the provider DELETE happens afterwards, and a row lock would be
        released at COMMIT and at crash. A worker that dies mid-delete loses its
        hold by EXPIRY, which is the only mechanism that survives the connection.

        `write_grace_seconds` is migration 0016's fourth argument, and passing it
        is not a formality -- it is what keeps the claim from collecting an
        object whose presigned upload URL is still live (ADR 0111).
        """
        rows = await self._all(
            "SELECT id, object_key, attempts "
            "FROM app_private.storage_claim_cleanup_batch(%s, %s, %s, %s)",
            (holder, limit, lease_seconds, write_grace_seconds),
        )
        return [
            CleanupClaim(
                object_id=row["id"], object_key=row["object_key"], attempts=int(row["attempts"])
            )
            for row in rows
        ]

    async def finish_cleanup(self, *, object_id: UUID, holder: str) -> bool:
        """Record that this holder collected the object. False if it no longer holds.

        False is not an error and the caller must not treat it as one: the
        worker's lease expired while it was working, somebody else claimed the
        object, and the honest report is "I no longer hold this" rather than
        "something failed". The work was still done -- and the second worker's
        DELETE is a no-op against an absent key, measured at 204 in Run 5.
        """
        row = await self._one(
            "SELECT app_private.storage_finish_cleanup(%s, %s) AS finished",
            (object_id, holder),
        )
        assert row is not None
        return bool(row["finished"])

    async def tombstone(self, *, object_id: UUID, owner_id: UUID) -> bool:
        """True when this call moved the object.

        False covers already-tombstoned, absent and another owner's alike, and
        the service answers all of them the same way. It does not answer 404 on
        a false: deleting something already deleted is the caller's intent
        already satisfied, and reporting that as absent would make DELETE
        non-idempotent for the owner.
        """
        row = await self._one(
            "SELECT app_private.storage_tombstone(%s, %s) AS moved",
            (object_id, owner_id),
        )
        assert row is not None
        return bool(row["moved"])
